---
run_id: date_tag:dev
iterations:
  - 0
  # - 1
  # - 2
fold:
  begin: 1
  end: 1
reproducibility:
  # rounds:
  #   - 0
  seed: 0
hp_tuning:
  enabled: true
  n_trials: 10
  # defaults:
  #   dropout: 0.123
  #   hidden_dim: 29
  #   epochs: 855
  #   opt_params:
  #     name: Adam
  #     params:
  #       lr: 0.001
  #       weight_decay: 0.011
gaston_freq_threshold: 0.1
# gaston_freq_threshold: 0.7
input_data_root: ./dataset
output_root: ./.output
dataset:
  src: egr
  data_class: Fullerenes
  # data_class: LogicDataset
  init_features:
    dim: 18
    strategy: static_random
  noise:
    type:
      - labels
    fraction: 0.25
  params:
    name: C60
    # name: c38-c1-3
    # name: c74-d3h
    # name: c84-d2-1
    # name: G600
    # name: C720-0
    # name: five_neighbors
    force_reload: true
    log: false
steps:
  - type: train
  - type: explain
    denoise_threshold: 20
  - type: annotate
    largest_frequent_pattern: 12
    maximal_only: false
    feature_importance:
      min_iteration: 1
      aggregation: sum
      threshold: median