apiVersion: v1
kind: Pod
metadata:
  name: egr-app
  namespace: hnaik2
  labels:
    app: egr-app
spec:
  dnsConfig:
    nameservers:
      - 8.8.8.8
  tolerations:
    - key: "V100"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
    - image: hnaik2/cuda-user:latest
      imagePullPolicy: Always
      name: egr-app
      args: ["/bin/bash", "/home/hnaik/git/egr/scripts/pod_startup.sh"]
      workingDir: /home/hnaik/git/egr
      env:
        - name: INSIDE_DOCKER
          value: "1"
        - name: EGR_SRC
          value: /home/hnaik/git/egr
        - name: PYTHONPATH
          value: /home/hnaik/git/egr:/home/hnaik/git/egr/apps/gnn_explainer
        - name: EGR_PY_HOME
          value: /home/hnaik/git/egr/.venv
      resources:
        limits:
          nvidia.com/gpu: "0"
        requests:
          memory: "100Mi"
      volumeMounts:
        - name: nfs-data
          mountPath: /data
        - name: nfs-home
          mountPath: /home
        - name: dshm
          mountPath: /dev/shm
  volumes:
    - name: nfs-data
      nfs:
        server: 10.2.100.1
        path: /data/nfs/hnaik2
    - name: nfs-home
      nfs:
        server: 10.2.100.1
        path: /data/nfs/hnaik2/sysroot/home
    - name: nfs-opt
      nfs:
        server: 10.2.100.1
        path: /data/nfs/hnaik2/sysroot/opt
    - name: dshm
      emptyDir:
        medium: Memory
  restartPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: egr-app-service
  namespace: hnaik2
spec:
  selector:
    app: egr-app
  type: NodePort
  ports:
    - name: jupyter
      port: 8082
      targetPort: 8080
      protocol: TCP
    - name: streamlit
      port: 8100
      targetPort: 8100
      protocol: TCP
    - name: prefect
      port: 4200
      targetPort: 4210
      protocol: TCP

---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: egr-app-ingress-port1
  namespace: hnaik2
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pods.evl.uic.edu`) && PathPrefix(`/egr`)
      kind: Rule
      priority: 1
      services:
        - name: egr-app-service
          port: 8082
    - match: Host(`pods.evl.uic.edu`) && PathPrefix(`/eegl`)
      kind: Rule
      priority: 2
      services:
        - name: egr-app-service
          port: 8100
    - match: Host(`pods.evl.uic.edu`) && PathPrefix(`/app`)
      kind: Rule
      priority: 3
      services:
        - name: egr-app-service
          port: 4200
