name: egr
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - coloredlogs
  - joblib
  - networkx
  - optuna
  - optuna-dashboard
  - pandas
  - pip
  - pyg::pyg
  - pytorch::pytorch
  - pytorch::pytorch-cuda==12.4
  - rdflib
  - scikit-learn
  - pip:
    - rclone
