apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: egr-data
spec:
  storageClassName: s3-storage
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi