apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
data:
  rclone.conf: |
    [ceph-s3]
    type = s3
    provider = Ceph
    env_auth = true
    access_key_id = <access_key>
    secret_access_key = <secret_key>
    endpoint = http://rook-ceph-rgw-centrals3.rook-central
    acl = private
