apiVersion: batch/v1
kind: Job
metadata:
  name: egr-test-job
spec:
  template:
    spec:
      containers:
      - name: egr-test-job
        image: hnaik/egr-nautilus:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: tmp-output
          mountPath: /output
        - name: tmp-cache
          mountPath: /cache
        resources:
          limits:
            memory: 6Gi
            cpu: 6
            nvidia.com/gpu: 1
          requests:
            memory: 4Gi
            cpu: 1
            nvidia.com/gpu: 1
      volumes:
      - name: tmp-input
        emptyDir: {}
      - name: tmp-output
        emptyDir:
          medium: Memory
      - name: tmp-cache
        emptyDir: {}
      - name: rclone-config
        configMap:
          name: rclone-config
      restartPolicy: Never
  backoffLimit: 5